# Generated by Django 4.2.3 on 2023-12-17 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('parent_grup', models.ManyToManyField(blank=True, to='core.grup')),
            ],
            options={
                'verbose_name': 'Grup',
                'verbose_name_plural': 'Grup',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nomor_whatsapp', models.CharField(max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kelas')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tagihan', models.CharField(max_length=255)),
                ('jumlah_tagihan', models.PositiveIntegerField()),
                ('time', models.DateField(default=django.utils.timezone.now, verbose_name='Waktu')),
                ('grup', models.ManyToManyField(blank=True, to='core.grup')),
                ('siswa', models.ManyToManyField(blank=True, to='core.siswa')),
                ('sudah_bayar', models.ManyToManyField(blank=True, related_name='sekeren', to='core.siswa')),
            ],
            options={
                'verbose_name': 'Tagihan',
                'verbose_name_plural': 'Tagihan',
            },
        ),
        migrations.CreateModel(
            name='TagihanDibayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.siswa')),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tagihan')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_whatsapp', models.CharField(max_length=30)),
                ('tagihan', models.ManyToManyField(to='core.tagihan')),
            ],
        ),
        migrations.AddField(
            model_name='grup',
            name='siswa',
            field=models.ManyToManyField(blank=True, to='core.siswa'),
        ),
    ]
