# Generated by Django 4.2.3 on 2023-12-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihandibayar',
            name='dibayar',
            field=models.BooleanField(default=False),
        ),
    ]
